### ISSUE TITLE
Add support for Dual200S

### ISSUE THREAD

**Issue by baghtal** [vlebourl/custom_vesync#124]
### Home Assistant log

<details><summary>Logs</summary>

```
2023-03-31 16:31:14.697 WARNING (MainThread) [homeassistant.components.vesync.fan] Humid-Defier - Unknown device type - Dual200S
```

</details>
[home-assistant_vesync_2023-03-31T22-36-45.148Z.log](https://github.com/vlebourl/custom_vesync/files/11127597/home-assistant_vesync_2023-03-31T22-36-45.148Z.log)

### Additional information

This looks like it might be a duplicate of #114 but I wanted to open the report in case it was a different underlying issue.

Thanks for the integration! I just bought the humidifer today just because you had made this, I look forward to using it :)

**Comment by Lasakro** [comment]
I installed v0.2.6 yesterday for my DUAL200S and got it working. I just need it to have a power button entity. I'll open a PR on that.
