### ISSUE TITLE
LV600S Humidifier Cannot set Mode (Auto/Normal/Sleep).  Setting seems to be ignored.

### ISSUE THREAD

**Issue by biver0** [vlebourl/custom_vesync#125]
If I go into the 3 dots on the Dashboard item, I get a dropdown where I can select Mode.  Auto/Normal/Sleep.  Choosing any of them results in the dropdown returning to it's initial state which is no mode selected.  

Also, nothing changes on the physical humidifier.  

Also, calling the service seems to do nothing as well.   I am unable to put the unit to sleep or take it out of sleep mode.

![Screenshot 2023-04-02 at 2 09 21 AM](https://user-images.githubusercontent.com/23388615/229343522-8cc5d0d2-12d2-4469-b1df-393dab1efad6.jpg)

**Comment by biver0** [comment]
This is definitely still present.  There are other oddities present here.  There seems to be some confusion about how sleep works.  As far as I can tell, (and there's some inconsistency about whether this works now from press to press,) Sleep just blanks the screen on the physical unit.  However, sleep is a specific modem that tells the until to go into "sleep" mode (not just blank the display.)  At the moment, sometimes when you choose the sleep, the screen blanks but that's all.... other times it doesn't respond.  Also the blank display doesn't always work.  Same as the Display switch often doesn't respond. 

I'd be willing to go feature by feature and test with you to help flush it out.

**Comment by biver0** [comment]
oops, not closed.

**Comment by vlebourl** [comment]
Hi! Thanks for your patience. I may have some time tomorrow evening to work on that! That would be around 10-11pm UTC.

**Comment by biver0** [comment]
Just to confirm (this is the very first time someone has quoted me UTC. I THINK it’s -7 for me in the US PST.Do that would be 3pm? Please confirm. On Apr 11, 2023, at 7:32 AM, Vincent Le Bourlot ***@***.***> wrote:﻿
Hi! Thanks for your patience. I may have some time tomorrow evening to work on that! That would be around 10-11pm UTC.

**Comment by biver0** [comment]
Sorry I didn't hear from you today.  You want to pick another time?

**Comment by vlebourl** [comment]
my bad, i completely forgot... can you join the discord? It will make it easier to discuss. https://discord.gg/DGZCkcPx

**Comment by biver0** [comment]
I’m in, what’s your Discord handle?

**Comment by igor-panteleev** [comment]
Hey there! I recently bought LV600S and face the same issue. I have prepared a [PR to fix this](https://github.com/vlebourl/custom_vesync/pull/136). It's been tested and works well.
