### ISSUE TITLE
The Dual 200S Needs an Entity like: switch.humidifier_power_switch

### ISSUE THREAD

**Issue by Lasakro** [vlebourl/custom_vesync#127]
### The problem

This needs to have a 10th entity stripped out for user use. Something like **switch.humidifier_power_switch** boolean. Great work so far.

### What version of this integration has the issue?

2.14

### What version of Home Assistant Core has the issue?

4.1

### Diagnostics

NA

### Home Assistant log

<details><summary>Logs</summary>

```py
Copy/paste any log here, between the starting and ending backticks.
```

</details>

**Comment by Lasakro** [comment]
Yes this still exists. Control from the device level, like in scripts, you can turn the device on and off. But at the entity level there is no on / off capable entity.

**Comment by Lasakro** [comment]
Yes this still exists.

**Comment by vlebourl** [comment]
Hi, thanks for the issue. I'm not sure to understand correctly what you want.
Furthermore, this doesn't make sense to me:
```
What version of this integration has the issue?
2.14

What version of Home Assistant Core has the issue?
4.1
```

Can you explain what you mean and provide the content of the diagnostics file?

**Comment by Lasakro** [comment]
Yes I'm using the above versions. There are only 3 Switch Entities available:
switch.200s_auto_mode
switch.200s_automatic_stop
switch.humidifier_display
But no switch to turn it on or off.

**Comment by vlebourl** [comment]
I'm not sure what integration you're using... Please provide the diagnostics file (go to Settings > Device and Services page, find the vesync integration, click the 3dots menu and Download diagnostics).

Here's what I have regarding versions:

About Home Assistant:
![image](https://user-images.githubusercontent.com/5701372/234818494-dcf0dad2-ee91-43a6-8e29-bd4c20202dbf.png)

"Home Assistant Core" refers to 2023.4.6. `4.1` doesn't make sense to me.

Intergration versions are here: https://github.com/vlebourl/custom_vesync/releases
`2.14` doesn't refere to any existing version...

**Comment by vlebourl** [comment]
I believe you are not using my custom integration, but rather the native one from home assistant. To use this component, please follow instructions here: https://github.com/vlebourl/custom_vesync/blob/main/README.md#installation

**Comment by Lasakro** [comment]
I appreciate the instructions about the Download Diagnostics. I didn't know what that was, now I do and attached. From the file I see that I have Home Assistant OS version is 4.6, Home Assistant Supervisor is 4.1, that's where I got that from.

I don't know where I got 2.14 from. Just to be sure I deleted the Integration I had, rebooted HA, and re-installed from your provided link (V0.2.8) and rebooted. I don't know why the attached file shows under custom components vesync 0.2.5 but there are still only 9 entities available, none being device on/off. 

[config_entry-vesync-ce2b4b257d7ddc1c7cf08461de3a2efb.json.txt](https://github.com/vlebourl/custom_vesync/files/11345648/config_entry-vesync-ce2b4b257d7ddc1c7cf08461de3a2efb.json.txt)

**Comment by vlebourl** [comment]
Hey, 
I updated the integration to v1.0.0 today, can you update and paste the diagnostics below? Use a code block like this:
 ` ```json `
 your diagnostics
 ` ``` `

**Comment by Lasakro** [comment]
I deleted the past integration, 0.2.8, and installed the one showing 1.0.0 at the top of the Github site. Not sure if it matters but my diagnostics, attached, still reads:
    "vesync": {
      "version": "0.2.5",
      "requirements": [
        "pyvesync==2.1.6"

I also still only have 9 entities. None named something like switch.humidifier_power.
[config_entry-vesync-7d9602c0237cf5008f98dfcc5e8427e7.json.txt](https://github.com/vlebourl/custom_vesync/files/11356243/config_entry-vesync-7d9602c0237cf5008f98dfcc5e8427e7.json.txt)

`{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.4.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/New_York",
    "os_name": "Linux",
    "os_version": "6.1.25",
    "supervisor": "2023.04.1",
    "host_os": "Home Assistant OS 10.1",
    "docker_version": "23.0.3",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "webrtc": {
      "version": "v3.1.0",
      "requirements": []
    },
    "vesync": {
      "version": "0.2.5",
      "requirements": [
        "pyvesync==2.1.6"
      ]
    },
    "smart_thermostat": {
      "version": "2021.11.1",
      "requirements": []
    },
    "localtuya": {
      "version": "5.0.0",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "vesync",
    "name": "VeSync",
    "codeowners": [
      "@markperdue",
      "@webdjoe",
      "@thegardenmonkey",
      "@vlebourl"
    ],
    "config_flow": true,
    "dhcp": [
      {
        "hostname": "levoit-*",
        "macaddress": "*"
      }
    ],
    "documentation": "https://www.home-assistant.io/integrations/vesync",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/vlebourl/custom_vesync",
    "requirements": [
      "pyvesync==2.1.6"
    ],
    "version": "0.2.5",
    "is_built_in": false
  },
  "data": {
    "humidifier": [
      {
        "device_name": "Humidifier",
        "device_image": "https://image.vesync.com/defaultImages/deviceDefaultImages/wifibtonboardingnotify_airhumidifier_dual200s_us_240.png",
        "cid": "**REDACTED**",
        "connection_status": "online",
        "connection_type": "WiFi+BTOnboarding+BTNotify",
        "device_type": "Dual200S",
        "type": "wifi-air",
        "uuid": "**REDACTED**",
        "config_module": "WiFiBTOnboardingNotify_AirHumidifier_Dual200S_US",
        "mac_id": "**REDACTED**",
        "mode": null,
        "speed": null,
        "extension": null,
        "current_firm_version": null,
        "device_region": "US",
        "pid": null,
        "sub_device_no": null,
        "config": {
          "auto_target_humidity": 30,
          "display": true,
          "automatic_stop": true
        },
        "device_status": "off",
        "enabled": true,
        "config_dict": {
          "module": "VeSyncHumid200300S",
          "models": [
            "Dual200S",
            "LUH-D301S-WUSR",
            "LUH-D301S-WJP",
            "LUH-D301S-WEU"
          ],
          "features": [],
          "mist_modes": [
            "auto",
            "manual"
          ],
          "mist_levels": [
            1,
            2
          ]
        },
        "mist_levels": [
          1,
          2
        ],
        "mist_modes": [
          "auto",
          "manual"
        ],
        "features": [],
        "warm_mist_feature": false,
        "warm_mist_levels": [],
        "night_light": false,
        "details": {
          "humidity": 56,
          "mist_virtual_level": 1,
          "mist_level": 1,
          "mode": "manual",
          "water_lacks": false,
          "humidity_high": false,
          "water_tank_lifted": false,
          "display": true,
          "automatic_stop_reach_target": true
        },
        "_api_modes": [
          "getHumidifierStatus",
          "setAutomaticStop",
          "setSwitch",
          "setNightLightBrightness",
          "setVirtualLevel",
          "setTargetHumidity",
          "setHumidityMode",
          "setDisplay",
          "setLevel"
        ]
      }
    ]
  }
}`

**Comment by Lasakro** [comment]
Entities:
![Entities](https://user-images.githubusercontent.com/14164409/235223121-3f4e6dc2-7c64-40aa-a1f8-96ae2c1da014.png)

**Comment by Lasakro** [comment]
Yes, still present.

**Comment by vlebourl** [comment]
Hi,

Your diagnostics show you are not using the custom integration... Otherwise it would show 1.0.0 as shown here https://github.com/vlebourl/custom_vesync/blob/2e2f77a95ea471d4717e4bff2dc6b1c0f7c6bd66/custom_components/vesync/manifest.json#L16

Can you post a screenshot of the integration page showing the vesync installation? It should show a box icon (see the README). 

To make sure you use the correct one, please do the following:
- uninstall the currently installed integration
- uninstall the HACS package
- restart home assistant
- install the HACS package
- restart home assistant
- install the vesync integration. Make sure the integration has the box icon 
![Screenshot_20230506-112115](https://user-images.githubusercontent.com/5701372/236615532-37211ad5-5508-4773-9829-aab136c3ba36.png)

**Comment by Lasakro** [comment]
[config_entry-vesync-7d9602c0237cf5008f98dfcc5e8427e7.json.txt](https://github.com/vlebourl/custom_vesync/files/11412650/config_entry-vesync-7d9602c0237cf5008f98dfcc5e8427e7.json.txt)
![vsync](https://user-images.githubusercontent.com/14164409/236632468-9d9be90c-8600-46c5-82a9-771f095030e4.png)

**Comment by vlebourl** [comment]
Okay, now we have the correct version
```json
"vesync": {
      "version": "1.0.0",
      "requirements": [
        "pyvesync==2.1.6"
      ]
    }
```
Regarding the entities, 9 is correct. 
I have the same humidifier (LUH-D301S-WEU in my case) and also 9 entities:
![Screenshot_20230506-171746](https://user-images.githubusercontent.com/5701372/236632825-d22f90a4-7e09-44f1-878a-da028ce52a33.png)

But no on/off switch entity because the on/off is directly controlled by humidifier entity. 

![Screenshot_20230506-171818](https://user-images.githubusercontent.com/5701372/236632855-fd27b24a-8f80-4b37-b82f-ff35d4de51ba.png)

I won't add a switch entity for that because that would be an extra entity for something already covered. If you absolutely need that entity and can't do it with the humidifier entity, you can have a look at template switches (https://www.home-assistant.io/integrations/switch.template/) using those services to control your template switch

![Screenshot_20230506-172135](https://user-images.githubusercontent.com/5701372/236632973-7b8a7d38-cbfd-4fe2-9183-79bd01133cb6.png)

I'll close this issue now as I believe we covered the matter.
Cheers

**Comment by Lasakro** [comment]
Without a 10th entity being on/off there is not a way to graph the state of on/off nor control it from plugin's and automatons which require a switch.some_entity. For the simple functions yes you can control power from the device level, for advance functions you can not. Are you still unwilling to strip out the power entity from the device?

**Comment by vlebourl** [comment]
I don't understand your problem... The start of the humidifier does reflect the on/off state and can be used in a graph of your choosing.
![Screenshot_20230506-201241](https://user-images.githubusercontent.com/5701372/236641248-4ba14f7a-3392-46fe-b3ac-5e4b16e07463.png)
![Screenshot_20230506-201647](https://user-images.githubusercontent.com/5701372/236641250-e51d4756-57c8-4216-b980-452dc7cc1d73.png)

If it helps, here's an automation using either the device or the service

```yaml
alias: "Humidifier: on/off"
description: ""
trigger:
  - platform: numeric_state
    entity_id: humidifier.humidificateur
    attribute: current_humidity
    above: 60
    id: Stop
  - platform: numeric_state
    entity_id: humidifier.humidificateur
    attribute: current_humidity
    below: 40
    id: Start
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: Start
        sequence:
          - type: turn_on
            device_id: 3e74d70ba4ad2af8c97b4a563d3268b1
            entity_id: humidifier.humidificateur
            domain: humidifier
      - conditions:
          - condition: trigger
            id: Stop
        sequence:
          - service: humidifier.turn_off
            data: {}
            target:
              entity_id: humidifier.humidificateur
mode: single
```

If you still can't achieve your result with this and still need a dedicated switch, then your use case is too specific to justify adding the switch to this integration as every standard use case is already covered. A template switch should cover your needs. In your configuration.yaml, you can add something along the lines of:

```yaml
switch:
  platform: template
  switches:
    humidifier_switch:
      value_template: "{{ is_state('humidifier.my_humidifier', 'on') }}"
      turn_on:
        service: humidifier.turn_on
        target:
          entity_id: humidifier.my_humidifier
      turn_off:
        service: humidifier.turn_off
        target:
          entity_id: humidifier.my_humidifier
```
