### ISSUE TITLE
Add Support for Air Fryers

### ISSUE THREAD

**Issue by KyleStilkey** [vlebourl/custom_vesync#144]
### Additional information

Just got my Air Fryer replacement and see it's not being pulled. I got a CS168-AF. I see last week you updated to support Air Fryers but I do not see it showing. I'm just unaware of its just needs to be added or if we are still waiting on PyPreSync fixes.

I think at least posting this here too will help keep all Air Fryer requests in one place too if we are just waiting.

**Comment by vlebourl** [comment]
Hi, 
I'm dependent on the devices being added to this file: https://github.com/webdjoe/pyvesync/blob/master/src/pyvesync/vesyncfan.py

Can you check if yours is in? If it's not, you can open an issue there to ask for addition.
If it is, I have a bug 😅

**Comment by KyleStilkey** [comment]
I think you meant to link me the kitchen list not fan. https://github.com/webdjoe/pyvesync/blob/master/src/pyvesync/vesynckitchen.py

The 158-AF is in the list which I still have technically just offline but it's in the app, not sure if it needs to be on (going to fix their cheap wiring before I attempt to use again due to recall issues) but the 168-AF is not listed, I'm not sure if just adding this to the model list would make it work or more has to be done, just waking up and not even fully thinking right now lol.

If this should be pulling the 158-AF even if the device is offline then yes there is a issue there as well but the 168-AF is missing.

I also posted on the Air Fryer open issue about the 168-AF too.

**Comment by vlebourl** [comment]
oh it's not a humidifier??? my bad!
I don't even know how to integrate air fryers TBH.
But I'm happy to have a look. Do you know what the Air Fryer is supposed to be in Home Assistant?

**Comment by KyleStilkey** [comment]
To be honest I am unsure, I can't get vs code to even run the test 

> 

To be honest I am unsure what you mean by what it's supposed to be in Home Assistant.
