### ISSUE TITLE
Levoit core 300s smart true hepa air purifier

### ISSUE THREAD

**Issue by choportrend** [vlebourl/custom_vesync#150]
### The problem

Hi guys. I recently bought a Levoit Smart Air Purifier 300s. 4 days into home assistant and I’ve gotten everything in my room synced up except this.

I’ve downloaded the official integration, however my purifier does not show up. It’s already linked to my VeSync account and I see the purifier there. I’ve also tried uninstalling the official integration, and downloading the custom vesync integration instead. No dice.

I’ve tried calling the service VeSync: Update devices from Developer Tools and yet still no device showing up.

Very new to HA, would appreciate any help! Also unsure of what details to add regarding my build, but I am on Home Assistant OS on a RPi4.

### What version of this integration has the issue?

v1.0.0

### What version of Home Assistant Core has the issue?

2023.6.3

### Diagnostics

<details><summary>Diagnostics</summary>

```{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.6.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Asia/Manila",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.06.4",
    "host_os": "Home Assistant OS 10.3",
    "docker_version": "23.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "climate_template": {
      "version": "0.6.1",
      "requirements": []
    },
    "localtuya": {
      "version": "5.2.1",
      "requirements": []
    },
    "vesync": {
      "version": "1.0.0",
      "requirements": [
        "pyvesync==2.1.6"
      ]
    },
    "pyscript": {
      "version": "1.4.0",
      "requirements": [
        "croniter==1.3.8",
        "watchdog==2.2.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "vesync",
    "name": "VeSync",
    "codeowners": [
      "@markperdue",
      "@webdjoe",
      "@thegardenmonkey",
      "@vlebourl"
    ],
    "config_flow": true,
    "dhcp": [
      {
        "hostname": "levoit-*",
        "macaddress": "*"
      }
    ],
    "documentation": "https://www.home-assistant.io/integrations/vesync",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/vlebourl/custom_vesync",
    "requirements": [
      "pyvesync==2.1.6"
    ],
    "version": "1.0.0",
    "is_built_in": false
  },
  "data": {}
}
```

</details>

### Home Assistant log

<details><summary>Logs</summary>

```py
Copy/paste any log here, between the starting and ending backticks.
```

</details>

**Comment by vlebourl** [comment]
Hi, sorry for the inconvenience... I suspect they your device may not be recognized by the underlying library, in which case there is nothing I can do on my end until it is.
Can you activate debug logging (see the README for the instructions), restart home assistant and look in the logs for any information?

**Comment by choportrend** [comment]
Hi there! This is what shows up under Settings -> System -> Logs

**
<img width="1130" alt="image" src="https://github.com/vlebourl/custom_vesync/assets/137311929/559b4282-a36c-4dcf-b5ce-acd16da2f73c">
**

It's quite odd because the device model itself is stated as being supported here in the documentation for the official integration:

![Uploading image.png…]()

**Comment by vlebourl** [comment]
Thing is, as you can see here: https://github.com/webdjoe/pyvesync/blob/308a988246c7f79b8838dc0e67f040dbe01ce61d/src/pyvesync/vesyncfan.py#L66

Same name can correspond to different device. We rely on the 'models' part that can have a lot of different values for the same kind of device. I suspect yours might not be listed...

**Comment by choportrend** [comment]
i see. alright, thank you for the info and help!
