### ISSUE TITLE
Integration broken after HA update.

### ISSUE THREAD

**Issue by hmjgriffon1** [vlebourl/custom_vesync#156]
Upgraded to the following:
 Home Assistant 2023.8.0
 Supervisor 2023.07.1
 Operating System 10.4
Frontend 20230802.0 - latest

Integration no longer works, I get these errors in the HA log.

Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:624
Integration: Switch (documentation, issues)
First occurred: 7:54:20 AM (4 occurrences)
Last logged: 7:54:20 AM

Ignoring invalid device info: Invalid device info {'default_manufacturer': 'VeSync', 'identifiers': {('vesync', 'vsaqfbd52134d318cb56214b183a69aa')}, 'model': 'LAP-C601S-WUS', 'name': 'Master Bedroom Levoit Air Purifier', 'sw_version': None} for 'vesync' config entry: device info needs to either describe a device, link to existing device or provide extra information.
Ignoring invalid device info: Invalid device info {'default_manufacturer': 'VeSync', 'identifiers': {('vesync', 'vsaq3782ffc40cd8f5457a1fd7956d79')}, 'model': 'LAP-C601S-WUS', 'name': 'Living Room Levoit Air Purifier', 'sw_version': None} for 'vesync' config entry: device info needs to either describe a device, link to existing device or provide extra information.

**Comment by RobertD502** [comment]
Are you sure this is for the VeSync integration? These look like entities for a Tempest weather station?

**Comment by modelstudent101** [comment]
They posted the wrong logs, but I was getting an error after the update that the device did not exist. After removing the device via the integration, I restarted, and re-added my account; the device was not created (300S Humidifer), but the entities were.

**Comment by NickM-27** [comment]
It is a problem, and https://github.com/vlebourl/custom_vesync/pull/154 fixed it

**Comment by modelstudent101** [comment]
Awesome, thank you for the alert.

@hmjgriffon1 — if you want an easy way to add pull requests to a custom component, check out this repository:
[Repo: /alandtse/pr_custom_component](https://github.com/alandtse/pr_custom_component)

Be extra careful when adding pull requests.

**Comment by hmjgriffon1** [comment]
Sorry guys, I don't know how I grabbed the wrong logs. I will look at the link, I rebooted and mine is working again but only have entities.

**Comment by hmjgriffon1** [comment]
so is that link an update that will come out?

**Comment by RobertD502** [comment]
> so is that link an update that will come out?

No, it is a pull requests that needs to be merged by the owner of this repo prior to creating a new release in order for it to be part of the next release.

**Comment by hmjgriffon1** [comment]
> > so is that link an update that will come out?
> 
> No, it is a pull requests that needs to be merged by the owner of this repo prior to creating a new release in order for it to be part of the next release.

thought so, thank you sir, and I updated my post with the correct log entry lol.

**Comment by vlebourl** [comment]
This will be out quickly!
Thanks for the report and the fix.

**Comment by cagnulein** [comment]
is this on the latest HASS version? i just updated HASS but the error still here :(

**Comment by cagnulein** [comment]
@vlebourl this my error with the latest HASS

`vesync: Not adding entity with invalid device info: Invalid device info {'default_manufacturer': 'VeSync', 'identifiers': {('vesync', 'vsaq73b8946141fd9fb15db29947e059')}, 'model': 'Core400S', 'name': 'Candeggiami', 'sw_version': None} for 'vesync' config entry: device info needs to either describe a device, link to existing device or provide extra information.`

**Comment by vlebourl** [comment]
> 'default_manufacturer': 'VeSync'

I don't think you are using the latest version as this string isn't in the code anymore since version 1.0.2.

**Comment by cagnulein** [comment]
sorry @vlebourl all fixed now, you were right: my HACS didn't prompt me for an update of your component. I had to remove the folder and reinstall it. Thanks for your quick support!
