### ISSUE TITLE
Add support for ... 200S

### ISSUE THREAD

**Issue by DeanSesko** [vlebourl/custom_vesync#166]
### Home Assistant log

<details><summary>Logs</summary>

```
Logger: custom_components.vesync.common
Source: custom_components/vesync/common.py:78
Integration: VeSync
First occurred: 12:24:18 AM (1 occurrences)
Last logged: 12:24:18 AM

Unknown device type Living Room 200S LAP-V201S-WUS (enable debug for more info)
```

</details>

**Comment by tismofied** [comment]
This please if possible

**Comment by DNARNA** [comment]
Also not seeing any device added to home assistant after installing the custom vesync integration through HACS.

**Comment by vlebourl** [comment]
new version of the integration has been released, please try it and close if it fixes the issue.

**Comment by DNARNA** [comment]
> new version of the integration has been released, please try it and close if it fixes the issue.

It's working after updating to v1.2.0!  Both entities have been added to my home assistant. Thanks for your help resolving the issue!

**Comment by DNARNA** [comment]
Thanks Vincent. Your change solved my issues and I can now control both of
my 200S devices. I'm not sure how to close the issue in GitHub? Is it
because I didn't originally create it?

Alex
