### ISSUE TITLE
Add support for LEVOIT H13

### ISSUE THREAD

**Issue by bannert1337** [vlebourl/custom_vesync#168]
### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Found the following devices:".
```

</details>

### Additional information

[Amazon](https://amzn.eu/d/brAaHar)

**Comment by vlebourl** [comment]
new version of the integration has been released, please try it and close if it fixes the issue.

**Comment by bannert1337** [comment]
Thank you very much. Now the device is properly detected.
