### ISSUE TITLE
Sleep mode?

### ISSUE THREAD

**Issue by totalitarian** [vlebourl/custom_vesync#23]
Love this competent. Any option to set sleep mode on the air purifiers?

**Comment by vlebourl** [comment]
Could probably be done, although I don't own any, so it may be hard. 
Feel free to join in here to discuss it further https://discord.gg/aAPhTVeQ

**Comment by sbelongie** [comment]
I am willing to help on this and improve this addon if needed.

**Comment by sbelongie** [comment]
not sure if this helps but you can call a service to set sleep mode.

service: fan.set_preset_mode
data:
  preset_mode: sleep
target:
  device_id: {device_id}

**Comment by vlebourl** [comment]
Not sure I understand the problem, if sleep mode is available through a service, then it should also be available through the UI, no?

**Comment by sbelongie** [comment]
That is correct @vlebourl I have it working no problem though the UI in home assistant.

**Comment by vlebourl** [comment]
I guess we can close this then. @totalitarian, feel free to reopen with more details if you still have an issue.
