### ISSUE TITLE
Filter Life and Child Lock

### ISSUE THREAD

**Issue by omurphy522** [vlebourl/custom_vesync#36]
Thank you guys for the custom integration. 

device: core300s

Any thoughts to adding filter life sensor and possibly the ability to set the child lock? 

It looks like these entities are available under the device attributes. I know I can make a template for the filter life and probably will attempt when I have time, if that is helpful to providing a more robust integration I’ll be happy to share it.

The child lock shows up, but I’m not sure if it’s possible to control it.

If this isn’t possible let me know and feel free to close this!

thank you!

**Comment by vlebourl** [comment]
Could you try the branch in #37?

**Comment by omurphy522** [comment]
I downloaded and added the branch in #37 deleted the integration, restarted, enabled the integration and still only see 1 device with 4 entities  

![image](https://user-images.githubusercontent.com/8385953/179368210-c13e2229-2485-42a3-9b29-8355719dff79.png)

**Comment by omurphy522** [comment]
I still only see the 4 entities as before.

I verified I am running the updated code as well.

Thank you

Owen

**Comment by vlebourl** [comment]
I don't know why this doesn't work. Could you post the diagnostics?
You should not need to delete and reinstall the integration, a simple restart of HA after updating should be enough.

**Comment by omurphy522** [comment]
Happy to whatever helps you out. 

I redownloaded the missing-features branch and uploaded the replaced the vesync folder then restarted HA.

I still only see the 4 entities.

Here is the diagnostic file. Let me know if you need anything else.


[config_entry-vesync-6fc47f349f7bed75ef68d52eb73c66ee.json (2).txt](https://github.com/vlebourl/custom_vesync/files/9128852/config_entry-vesync-6fc47f349f7bed75ef68d52eb73c66ee.json.2.txt)

**Comment by vlebourl** [comment]
thanks for the diagnostics. can you try again?
