### ISSUE TITLE
Air quality value is different than the raw value

### ISSUE THREAD

**Issue by danieletorelli** [vlebourl/custom_vesync#47]
Hello, since the 0.1.15 version the Air Quality sensor shows a different value than the raw value visible in the app.

The data shows:
![image](https://user-images.githubusercontent.com/2891141/185414108-a068a892-5a94-4e90-be8c-4aa6ba6bb9d3.jpeg)

As you can see from the screenshot the value is fetched correctly but the sensor value shows `1` now instead of `5`.

**Comment by vlebourl** [comment]
can you try version 0.1.16-beta? 
In HACS, open custom vesync, click redownload and activate show beta version.

**Comment by danieletorelli** [comment]
> can you try version 0.1.16-beta? 
> 
> In HACS, open custom vesync, click redownload and activate show beta version.
> 
> 

Done. The issue persists also with the beta version:

![image](https://user-images.githubusercontent.com/2891141/185415955-f742205f-ff6a-4376-98f5-072bd685a6e6.jpeg)
![image](https://user-images.githubusercontent.com/2891141/185416008-7455abb2-b682-4a81-8316-3536dcc60c71.jpeg)

Downgrading to version 0.1.14 solved it for now, so I believe it should be a regression introduced in the 0.1.15.

![image](https://user-images.githubusercontent.com/2891141/185416320-30066c28-373c-4ff0-bade-c19100fed8b3.jpeg)

**Comment by vlebourl** [comment]
Could you post your diagnostics?
I made a change prioritizing `air_quality` over `air_quality_value` if both are present. I'd like to understand what the difference is.

**Comment by danieletorelli** [comment]
> Could you post your diagnostics?
> 

Here are the two diagnostics.

<details>
<summary>0.1.14</summary>

```json
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2022.8.5",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "5.18.1-1-aarch64-ARCH",
    "run_as_root": true
  },
  "custom_components": {
    "meross_lan": {
      "version": "2.6.1",
      "requirements": []
    },
    "vesync": {
      "version": "0.1.3",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "vesync",
    "name": "VeSync",
    "documentation": "https://www.home-assistant.io/integrations/vesync",
    "codeowners": [
      "@markperdue",
      "@webdjoe",
      "@thegardenmonkey",
      "@vlebourl"
    ],
    "config_flow": true,
    "iot_class": "cloud_polling",
    "version": "0.1.3",
    "issue_tracker": "https://github.com/vlebourl/custom_vesync",
    "dhcp": [
      {
        "hostname": "levoit-*",
        "macaddress": "*"
      }
    ],
    "is_built_in": false
  },
  "data": {
    "fans": [
      {
        "config_dict": {
          "module": "VeSyncAirBypass",
          "models": [
            "Core300S",
            "LAP-C301S-WJP"
          ],
          "modes": [
            "sleep",
            "off",
            "auto"
          ],
          "features": [
            "air_quality"
          ],
          "levels": [
            1,
            2,
            3,
            4
          ]
        },
        "config": {
          "display": true,
          "display_forever": true
        },
        "details": {
          "filter_life": 94,
          "mode": "manual",
          "level": 0,
          "display": false,
          "child_lock": false,
          "night_light": "off",
          "air_quality": 1,
          "display_forever": false,
          "air_quality_value": 5
        }
      }
    ],
    "outlets": [],
    "switches": [],
    "bulbs": []
  }
}
```
</details>
<details>
<summary>0.1.16b</summary>

```json

{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2022.8.5",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "5.18.1-1-aarch64-ARCH",
    "run_as_root": true
  },
  "custom_components": {
    "meross_lan": {
      "version": "2.6.1",
      "requirements": []
    },
    "vesync": {
      "version": "0.1.15",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "vesync",
    "name": "VeSync",
    "documentation": "https://www.home-assistant.io/integrations/vesync",
    "codeowners": [
      "@markperdue",
      "@webdjoe",
      "@thegardenmonkey",
      "@vlebourl"
    ],
    "config_flow": true,
    "iot_class": "cloud_polling",
    "version": "0.1.15",
    "issue_tracker": "https://github.com/vlebourl/custom_vesync",
    "dhcp": [
      {
        "hostname": "levoit-*",
        "macaddress": "*"
      }
    ],
    "is_built_in": false
  },
  "data": {
    "fans": [
      {
        "device_name": "Purificatore",
        "device_image": "https://image.vesync.com/defaultImages/deviceDefaultImages/wifibtonboardingnotify_airpurifier_core300s_eu_240.png",
        "cid": "**REDACTED**",
        "connection_status": "online",
        "connection_type": "WiFi+BTOnboarding+BTNotify",
        "device_type": "Core300S",
        "type": "wifi-air",
        "uuid": "**REDACTED**",
        "config_module": "WiFiBTOnboardingNotify_AirPurifier_Core300S_EU",
        "mac_id": "**REDACTED**",
        "mode": "auto",
        "speed": 2,
        "extension": {
          "airQuality": -1,
          "airQualityLevel": 1,
          "mode": "auto",
          "fanSpeedLevel": "255"
        },
        "current_firm_version": null,
        "sub_device_no": null,
        "config": {
          "display": true,
          "display_forever": true
        },
        "device_status": "off",
        "enabled": false,
        "config_dict": {
          "module": "VeSyncAirBypass",
          "models": [
            "Core300S",
            "LAP-C301S-WJP"
          ],
          "modes": [
            "sleep",
            "off",
            "auto"
          ],
          "features": [
            "air_quality"
          ],
          "levels": [
            1,
            2,
            3,
            4
          ]
        },
        "features": [
          "air_quality"
        ],
        "modes": [
          "sleep",
          "off",
          "auto"
        ],
        "air_quality_feature": true,
        "details": {
          "filter_life": 94,
          "mode": "manual",
          "level": 0,
          "display": false,
          "child_lock": false,
          "night_light": "off",
          "air_quality": 1,
          "display_forever": false,
          "air_quality_value": 5
        }
      }
    ]
  }
}
```
</details>

> I made a change prioritizing `air_quality` over `air_quality_value` if both are present. I'd like to understand what the difference is.
> 
>

So far I understood, the value is the most important (shown also in the official app) because it indicates the particles per μg/m³.

**Comment by vlebourl** [comment]
So we don't know what this means? 
`"air_quality": 1,`

I'll change the order to prioritize the value. Some air purifier don't have that key and still need to read `air_quality`, hence me adding it.

**Comment by danieletorelli** [comment]
> So we don't know what this means? 
> 
> `"air_quality": 1,`
> 
> 
> 
> I'll change the order to prioritize the value. Some air purifier don't have that key and still need to read `air_quality`, hence me adding it. 

It's the level of how bad is the air in the colored scale from `1` (blue) to `4` (red) indicated with the different colors in this diagram from the official app.

![image](https://user-images.githubusercontent.com/2891141/185425006-5c1d2635-a085-417a-8a1e-7a109729932c.jpeg)

**Comment by vlebourl** [comment]
Oh I see! and the value, is an int or a float?

**Comment by danieletorelli** [comment]
> Oh I see! and the value, is an int or a float?

To me it looks definitely an int, in both cases. Or at least this is how the official app is rendering the value one.

**Comment by danieletorelli** [comment]
BTW, I also have an issue with the speed levels: in the app and physically I have 3 speeds in manual mode, but the integration for some reason is showing 4.

Do you want me to open a dedicated issue?

**Comment by vlebourl** [comment]
yes please. And at some point, I might ask you for access to your device to debug it as it's tough to do it without owning the thing...

**Comment by vlebourl** [comment]
But TBH, I'm not sure that's a bug on my side, as your diagnostics show this: 
```json
          "levels": [
            1,
            2,
            3,
            4
          ]
```
which is where I take the speeds from... Not much I can do as those come from the underlying API...
