### ISSUE TITLE
support for cosori air fryers?

### ISSUE THREAD

**Issue by smenzer** [vlebourl/custom_vesync#49]
I just installed this custom integration because I purchased the Dual 200S humidifier. I also already have a Cosori Pro II Smart Air Fryer (model CS358-AF I believe) that I have hooked up to Vesync. However, in both the standard vesync integration and this one, I don't see the device show up. Do you have any plans to support this air fryer?

**Comment by vlebourl** [comment]
Hey, as I only own a humidifier, I had no knowledge of your device. There's no objection of principle but I would need more details, firstly whether it's supported by the underlying library.

**Comment by smenzer** [comment]
> firstly whether it's supported by the underlying library 

do you mean the standard vesync library? or the underlying python library?

**Comment by vlebourl** [comment]
The pyvesync python lib. I have no hand on it, so if it's not supported yet, you should ask for it first. Otherwise, if you activate debug log for both the integration and the python lib, you should get some info on that device that you can post here.

**Comment by vlebourl** [comment]
https://github.com/webdjoe/pyvesync/issues/55
