### ISSUE TITLE
Install via links to HACS failed

### ISSUE THREAD

**Issue by borpin** [vlebourl/custom_vesync#5]
Hi,

Tried the links in the readme to install via HACS and it did not install correctly.  Did not appear on HACS Integrations page and did not seem to download the repository into the `custom_component` folder.

It appeared to install the main VeSync component.

Adding the URL manually to HACS worked and automatically picked up the configuration of the core component.

It also showed a v0.1.0 and a `main` as options to install (when beta selected).

**Comment by vlebourl** [comment]
This repo isn't registered on hacs so it won't show up without adding the url to hacs. The readme maybe unclear, I'll have a look.

**Comment by vlebourl** [comment]
Readme states 
> This integration can be installed by adding this repository to HACS, then searching for VeSync and choosing install. 

Should this be made more explicit in your opinion?

**Comment by borpin** [comment]
> Should this be made more explicit in your opinion?

It was the my Home Assistant link that I tried. I was hoping this would add the repo. Rereading the text, I realise I made a mistake and misread. Sorry.
