### ISSUE TITLE
Add support for LUH-O451S-WUS

### ISSUE THREAD

**Issue by jeffphilly** [vlebourl/custom_vesync#58]
### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Found the following devices:".
```

</details>

### Additional information

Was recently added to the underlying library

**Comment by vlebourl** [comment]
Hi, I just published a new release with a refactored device detection that should work on your device as well. 
I'll close this issue for now, please reopen if v0.2.0 doesn't fix it.

**Comment by jeffphilly** [comment]
Thanks. I have put an issue in, not sure if it is user error or an issue with the version I have installed from HACS
