### ISSUE TITLE
Add support for setting mode in device action for Core 300S

### ISSUE THREAD

**Issue by vlebourl** [vlebourl/custom_vesync#59]
following #57

**Comment by vlebourl** [comment]
@crypticviper how do you like this???
![image](https://user-images.githubusercontent.com/5701372/200787861-9b3cceea-9713-4700-9931-c9028855643a.png)

**Comment by crypticviper** [comment]
Looks perfect to me 👍

**Comment by vlebourl** [comment]
can you test the branch in #62?

**Comment by crypticviper** [comment]
I am sorry, but how do I test a specific branch?

**Comment by vlebourl** [comment]
It's merged into main. In HACS, select Redownload, and in version choose main. 
Let me know here how it works, and if it's fine I'll publish a new release.

**Comment by crypticviper** [comment]
Will do that, thanks.

**Comment by crypticviper** [comment]
@vlebourl  Tested my scenarios. Seems to be working fine.
