### ISSUE TITLE
Add support for LV600S 

### ISSUE THREAD

**Issue by d0wniz** [vlebourl/custom_vesync#66]
### Home Assistant log

I get an error for my LV600S:

Logger: homeassistant.components.vesync.fan
Source: components/vesync/fan.py:67
Integration: VeSync ([documentation](https://rc.home-assistant.io/integrations/vesync), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+vesync%22))
First occurred: 9:18:58 AM (1 occurrences)
Last logged: 9:18:58 AM
Lufti - Unknown device type - LUH-A602S-WEU

</details>

**Comment by vlebourl** [comment]
Hi, 
This device should already be included in the component. Could you open a bug report with all the relevant information, particularly the diagnostics? 
Cheers
