### ISSUE TITLE
Dual 200S humidifier nightlight does not seem to be working

### ISSUE THREAD

**Issue by Valdorama** [vlebourl/custom_vesync#81]
### The problem

I recently purchased the Dual 200S humidifier and after registering it with the VeSync app on my phone, it is correctly picked up by the integration after restarting HA. Various entities are created for it and the basic controls (on/off) appear to be working.

A light entity is also created for the nightlight but it doesn't seem to work. The status is unknown:

![image](https://user-images.githubusercontent.com/34754485/215584555-ad558d54-e0c5-4ece-84de-326f8e2088b8.png)

Turning it on or off does not seem to work. I enabled debug logging for the integration but don't see anything in the logs.

### What version of this integration has the issue?

2.5.0

### What version of Home Assistant Core has the issue?

2023.1.7

### Diagnostics

<details><summary>Diagnostics</summary>

```json
{
        "device_name": "Kids Humidifier",
        "device_image": "https://image.vesync.com/defaultImages/deviceDefaultImages/wfon_ahm_luh-d301s-wusr_us_240.png",
        "cid": "**REDACTED**",
        "connection_status": "online",
        "connection_type": "WiFi+BTOnboarding+BTNotify",
        "device_type": "LUH-D301S-WUSR",
        "type": "wifi-air",
        "uuid": "**REDACTED**",
        "config_module": "WFON_AHM_LUH-D301S-WUSR_US",
        "mac_id": "**REDACTED**",
        "mode": null,
        "speed": null,
        "extension": null,
        "current_firm_version": null,
        "sub_device_no": null,
        "config": {
          "auto_target_humidity": 45,
          "display": true,
          "automatic_stop": true
        },
        "device_status": "off",
        "enabled": false,
        "config_dict": {
          "module": "VeSyncHumid200300S",
          "models": [
            "Dual200S",
            "LUH-D301S-WUSR",
            "LUH-D301S-WJP",
            "LUH-D301S-WEU"
          ],
          "features": [],
          "mist_modes": [
            "auto",
            "manual"
          ],
          "mist_levels": [
            1,
            2
          ]
        },
        "mist_levels": [
          1,
          2
        ],
        "mist_modes": [
          "auto",
          "manual"
        ],
        "features": [],
        "warm_mist_feature": false,
        "warm_mist_levels": [],
        "night_light": false,
        "details": {
          "humidity": 47,
          "mist_virtual_level": 1,
          "mist_level": 1,
          "mode": "manual",
          "water_lacks": true,
          "humidity_high": false,
          "water_tank_lifted": false,
          "display": false,
          "automatic_stop_reach_target": false
        },
        "_api_modes": [
          "getHumidifierStatus",
          "setAutomaticStop",
          "setSwitch",
          "setNightLightBrightness",
          "setVirtualLevel",
          "setTargetHumidity",
          "setHumidityMode",
          "setDisplay",
          "setLevel"
        ]
      }
```

</details>

### Home Assistant log

<details><summary>Logs</summary>

```py
Copy/paste any log here, between the starting and ending backticks.
```

</details>

**Comment by vlebourl** [comment]
Hi, 
Thanks for your report. The diagnostics show `"night_light": false` which means to my understanding that night light is not supported. I improved the code to prevent such an entity to appear if the underlying functionality isn't supported. 
This will be soon pushed to a new version. In the meantime, you can deactivate the entity to prevent it from appearing in your HA. 
Cheers

**Comment by Valdorama** [comment]
Thanks for looking into this. Sorry for commenting on a closed issue - I see that the PyVesync project seems to have [support](https://github.com/webdjoe/pyvesync#levoit-humidifier-methods-and-properties) for the night light (brightness). On the Dual200S model the night light is actually colour-changing so it could be perfect as a full colour-capable light entity. Would I need to raise an issue on that project to hopefully add full support for the night light?

**Comment by vlebourl** [comment]
> On the Dual200S model the night light is actually colour-changing

Strange! I have a Dual 200S at home as well, but no night light here... can you post a screenshot of the vesync app with the night light? 
Cheers

**Comment by vlebourl** [comment]
mine is actually a  LUH-D301S-WEU rather than LUH-D301S-WUSR. Maybe they have differences?

**Comment by Valdorama** [comment]
Yeah it could be a very new feature. The product page had no mention of it when I ordered it so it was a total surprise. Here's the screenshot:

![Screenshot_20230202-084141](https://user-images.githubusercontent.com/34754485/216356189-e358e4a7-db55-444f-8470-9c3410a91115.png)

**Comment by vlebourl** [comment]
nice ! how do you access it? sliding up from the main screen?

**Comment by vlebourl** [comment]
I can try to add the color mode. But I would need access to your device to test it all as mine doesn't have it. If you don't mind sharing it, can you send an invite at `vlebourl+vesync -at- gmail.com`, and let me know when it's possible to fiddle with it. 
I'm not gonna be able to have a look before next wednesday though. 
Cheers

**Comment by Valdorama** [comment]
It's on the main page for the humidifier, directly underneath the big circle that shows the current humidity level.

**Comment by Valdorama** [comment]
Sure I can do that. Let me know next week when you're free and I can share the device.
