### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by marcelbeh** [vlebourl/custom_vesync#83]
I tried adding this rep via HACS. However, it only works and does not add it. I used the GitHub link of the rep and selected integration as custom rep. 

Did I do something wrong?

**Comment by vlebourl** [comment]
Did you use the core integration first? 
You can try:

* remove integration from the settings -> integration page
* restart Home Assistant
* uninstall the custom component 
* restart Home Assistant
* install from HACS
* restart Home Assistant
* add the integration from the settings -> integration page. 

Verify that you have the little box icon on the right meaning you are indeed adding the custom integration. 

<img width="496" alt="image" src="https://user-images.githubusercontent.com/5701372/216333826-8348a2af-8092-4eed-86c3-e428fb8c6b58.png">

All the reboots are important to ensure proper cleanup after uninstalling.
If you still have trouble, please activate debug mode and post the relevant logs. 

Cheers

**Comment by marcelbeh** [comment]
The small box is not displayed to me. I only get the cloud displayed.

Do I need to enable or allow custom integrations ?

**Comment by marcelbeh** [comment]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/122119777/216373763-e4667fb8-a627-4d1a-b2dc-ecaf98259805.png">

The HACS integration has worked.

However, with the HA integration - as written above - only the cloud version is shown to me. A custom integration is not to be found there (the box is missing).

<img width="480" alt="image" src="https://user-images.githubusercontent.com/122119777/216374844-a759040b-24f2-4f74-88e1-41139ee35ecd.png">

**Comment by marcelbeh** [comment]
It works now... 😅
