### ISSUE TITLE
Supported Devices

### ISSUE THREAD

**Issue by baylanger** [vlebourl/custom_vesync#90]
### The problem

Hello,

If I'd know where to look I would do it ... can we add in the README the current list of supported devices?

I'm looking at buying Air Purifier 300S or 400S and for the Humidifier for next year.

It's not clear if this implementation supports only Humidifier and looking at old issues, it's confusing as some where left w/ no response from the original OP.

Does the integration runs w/o no cloud or still requires using the smart app w/ cloud?

Thanx.

### What version of this integration has the issue?

2.5.0

### What version of Home Assistant Core has the issue?

None

### Diagnostics

Air Purifier Vesync 300S & 400S

### Home Assistant log

None

### Additional information

None

**Comment by baylanger** [comment]
Looking at pyvesync repo, in that project the README has a list of supported devices.

Are all devices supported by pyvesync supported by custom_vesync?

**Comment by baylanger** [comment]
Figured out myself this integration needs vesync cloud to work :/ was hoping to have a no-cloud solution.

**Comment by vlebourl** [comment]
Hey, 
Indeed it's a cloud integration... I don't know any way to have a local version...
In theory, every device in the pyvesync lib should be supported by this. If not, I'm happy to take PR's or work with you on fixing your device support.
Cheers.
